export const fallbackCriteria = [
  ['1.1.1 Non-text Content (Level A)', 'A', 'Provide text alternatives for non-text content, except where content is decorative, a control, media, CAPTCHA, or otherwise exempt.'],
  ['1.2.1 Audio-only and Video-only (Prerecorded) (Level A)', 'A', 'Provide an alternative for prerecorded audio-only content and either an audio track or media alternative for prerecorded video-only content.'],
  ['1.2.2 Captions (Prerecorded) (Level A)', 'A', 'Provide captions for prerecorded synchronized audio in media.'],
  ['1.2.3 Audio Description or Media Alternative (Prerecorded) (Level A)', 'A', 'Provide audio description or a full media alternative for prerecorded video content.'],
  ['1.3.1 Info and Relationships (Level A)', 'A', 'Ensure information, structure, and relationships conveyed visually are also programmatically determinable or available in text.'],
  ['1.3.2 Meaningful Sequence (Level A)', 'A', 'Ensure content has a programmatically determinable reading and focus sequence that preserves meaning.'],
  ['1.3.3 Sensory Characteristics (Level A)', 'A', 'Do not rely only on sensory traits such as shape, size, visual location, orientation, or sound for instructions.'],
  ['1.4.1 Use of Color (Level A)', 'A', 'Do not use color as the only means to convey information, indicate action, prompt response, or distinguish elements.'],
  ['1.4.2 Audio Control (Level A)', 'A', 'Provide a way to pause, stop, or control audio that plays automatically for more than three seconds.'],
  ['2.1.1 Keyboard (Level A)', 'A', 'Ensure all functionality is operable through a keyboard interface without requiring specific keystroke timing.'],
  ['2.1.2 No Keyboard Trap (Level A)', 'A', 'Ensure keyboard focus can move into and out of every component using standard keyboard navigation.'],
  ['2.1.4 Character Key Shortcuts (Level A 2.1 and 2.2)', 'A', 'Allow single-character shortcuts to be turned off, remapped, or active only when the related control has focus.'],
  ['2.2.1 Timing Adjustable (Level A)', 'A', 'For time limits, allow users to turn off, adjust, or extend the limit unless an exception applies.'],
  ['2.2.2 Pause, Stop, Hide (Level A)', 'A', 'Allow users to pause, stop, hide, or control moving, blinking, scrolling, or auto-updating content when required.'],
  ['2.3.1 Three Flashes or Below Threshold (Level A)', 'A', 'Do not include content that flashes more than three times per second unless below the flash threshold.'],
  ['2.4.1 Bypass Blocks (Level A)', 'A', 'Provide a mechanism to bypass repeated blocks of content and reach the main content.'],
  ['2.4.2 Page Titled (Level A)', 'A', 'Provide web pages with titles that describe their topic or purpose.'],
  ['2.4.3 Focus Order (Level A)', 'A', 'Ensure focusable components receive focus in an order that preserves meaning and operability.'],
  ['2.4.4 Link Purpose (In Context) (Level A)', 'A', 'Ensure each link purpose can be determined from the link text alone or its programmatic context.'],
  ['2.5.1 Pointer Gestures (Level A 2.1 and 2.2)', 'A', 'Provide single-pointer alternatives for functionality that uses multipoint or path-based gestures unless exempt.'],
  ['2.5.2 Pointer Cancellation (Level A 2.1 and 2.2)', 'A', 'Ensure pointer actions can be cancelled, undone, or triggered on up-event unless an exception applies.'],
  ['2.5.3 Label in Name (Level A 2.1 and 2.2)', 'A', 'Ensure the accessible name of controls with visible text includes the visible label text.'],
  ['2.5.4 Motion Actuation (Level A 2.1 and 2.2)', 'A', 'Provide non-motion alternatives for functionality triggered by device or user motion and allow motion activation to be disabled.'],
  ['3.1.1 Language of Page (Level A)', 'A', 'Programmatically identify the default human language of each page.'],
  ['3.2.1 On Focus (Level A)', 'A', 'Do not trigger a change of context when a component receives focus.'],
  ['3.2.2 On Input (Level A)', 'A', 'Do not trigger unexpected context changes when a user changes a setting or field value.'],
  ['3.2.6 Consistent Help (Level A 2.2 only)', 'A', 'Keep help mechanisms in a consistent relative order across pages when they are provided.'],
  ['3.3.1 Error Identification (Level A)', 'A', 'Identify input errors and describe them to the user in text.'],
  ['3.3.2 Labels or Instructions (Level A)', 'A', 'Provide labels or instructions when content requires user input.'],
  ['3.3.7 Redundant Entry (Level A 2.2 only)', 'A', 'Do not require users to re-enter information already provided in the same process unless an exception applies.'],
  ['4.1.1 Parsing (Level A)', 'A', 'Use markup that can be parsed reliably, including proper nesting, unique IDs, and complete start/end tags.'],
  ['4.1.2 Name, Role, Value (Level A)', 'A', 'Expose the name, role, states, properties, and values of user interface components programmatically.'],
  ['1.2.4 Captions (Live) (Level AA)', 'AA', 'Provide captions for live synchronized audio content.'],
  ['1.2.5 Audio Description (Prerecorded) (Level AA)', 'AA', 'Provide audio description for prerecorded synchronized video content.'],
  ['1.3.4 Orientation (Level AA 2.1 and 2.2)', 'AA', 'Do not restrict content to a single display orientation unless that orientation is essential.'],
  ['1.3.5 Identify Input Purpose (Level AA 2.1 and 2.2)', 'AA', 'Programmatically identify the purpose of input fields that collect information about the user.'],
  ['1.4.3 Contrast (Minimum) (Level AA)', 'AA', 'Ensure text and images of text meet minimum contrast ratios, with defined exceptions.'],
  ['1.4.4 Resize Text (Level AA)', 'AA', 'Allow text to resize up to 200 percent without loss of content or functionality.'],
  ['1.4.5 Images of Text (Level AA)', 'AA', 'Use real text instead of images of text unless the image is customizable or essential.'],
  ['1.4.10 Reflow (Level AA 2.1 and 2.2)', 'AA', 'Ensure content reflows without loss of information or functionality at 320 CSS pixels wide or equivalent zoom.'],
  ['1.4.11 Non-text Contrast (Level AA 2.1 and 2.2)', 'AA', 'Ensure essential graphical objects, controls, and states have sufficient non-text contrast.'],
  ['1.4.12 Text Spacing (Level AA 2.1 and 2.2)', 'AA', 'Support increased text spacing without loss of content or functionality.'],
  ['1.4.13 Content on Hover or Focus (Level AA 2.1 and 2.2)', 'AA', 'Ensure hover or focus-triggered content is dismissible, hoverable, and persistent unless exempt.'],
  ['2.4.5 Multiple Ways (Level AA)', 'AA', 'Provide more than one way to locate pages within a set of web pages unless exempt.'],
  ['2.4.6 Headings and Labels (Level AA)', 'AA', 'Use headings and labels that describe topic or purpose.'],
  ['2.4.7 Focus Visible (Level AA)', 'AA', 'Ensure keyboard focus is visually apparent.'],
  ['2.4.11 Focus Not Obscured (Minimum) (Level AA 2.2 only)', 'AA', 'Ensure focused user interface components are not entirely hidden by author-created content.'],
  ['2.5.7 Dragging Movements (Level AA 2.2 only)', 'AA', 'Provide a single-pointer alternative for functionality that requires dragging unless dragging is essential.'],
  ['2.5.8 Target Size (Minimum) (Level AA 2.2 only)', 'AA', 'Ensure pointer targets are at least 24 by 24 CSS pixels or meet an allowed exception.'],
  ['3.1.2 Language of Parts (Level AA)', 'AA', 'Programmatically identify changes in human language within content unless exempt.'],
  ['3.2.3 Consistent Navigation (Level AA)', 'AA', 'Keep repeated navigation mechanisms in the same relative order unless the user changes them.'],
  ['3.2.4 Consistent Identification (Level AA)', 'AA', 'Identify components with the same functionality consistently.'],
  ['3.3.3 Error Suggestion (Level AA)', 'AA', 'Provide correction suggestions for input errors when suggestions are known and appropriate.'],
  ['3.3.4 Error Prevention (Legal, Financial, Data) (Level AA)', 'AA', 'For important submissions, provide reversal, checking, or confirmation before finalizing.'],
  ['3.3.8 Accessible Authentication (Minimum) (Level AA 2.2 only)', 'AA', 'Do not require a cognitive function test for authentication unless an accessible alternative or exception applies.'],
  ['4.1.3 Status Messages (Level AA 2.1 and 2.2)', 'AA', 'Programmatically expose status messages so assistive technologies can announce them without moving focus.'],
].map(([criteria, level, requirementSummary]) => ({
  criteria,
  level,
  requirementSummary,
}));
