function cleanCell(value) {
  return String(value ?? '')
    .replace(/\r?\n/g, '<br>')
    .replace(/\|/g, '/')
    .trim();
}

export function makeMarkdown(tables, meta) {
  const lines = [
    '# SLFCP WCAG A/AA Conformance Assessment',
    '',
    `Report Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    '',
    'Product: Space Launch Frequency Coordination Portal (SLFCP)',
    '',
    'Scope: AI-assisted monorepo code assessment against WCAG 2.0, 2.1, and 2.2 Level A and Level AA criteria represented in the VPAT/WCAG source template.',
    '',
    `Source Template: ${meta.source.docxPath ?? 'Built-in WCAG A/AA criteria fallback used because no .docx source was found.'}`,
    '',
    `Criteria Source: ${meta.source.usedBuiltInCriteriaFallback ? 'Built-in fallback criteria because no known A/AA criteria were matched in the .docx.' : `${meta.source.docxCriteriaMatched} A/AA criteria matched from the .docx source template.`}`,
    '',
    `Evaluation Methods Used: AI-assisted source review of indexed monorepo files using ${meta.aiAudit.model}, supported by deterministic static signals and Playwright runtime evidence${meta.runtimeEvidence.available ? ` from ${meta.runtimeEvidence.routesVisited} route(s) and ${meta.runtimeEvidence.workflowsVisited ?? 0} scripted role workflow(s)` : ' when the configured backend and frontend are reachable'}. The runtime stage collects rendered titles, headings, landmarks, basic DOM accessibility signals, keyboard focus samples, scripted interaction snapshots, and axe-core browser findings. This iteration does not run WAVE, ANDI, Lighthouse, screen readers, full contrast analyzers, full zoom/reflow testing, or production authentication flows.`,
    '',
    '## Terms',
    '',
    'Supports: The reviewed static evidence indicates the criterion is met without known defects.',
    '',
    'Partially Supports: Some functionality appears to meet the criterion, but known or likely gaps remain.',
    '',
    'Mostly Supports: The reviewed functionality generally appears to meet the criterion, but additional verification or minor remediation is recommended before a formal claim.',
    '',
    'Does Not Support: The product appears not to meet the criterion for a major required behavior.',
    '',
    'Not Applicable: The criterion is not relevant to the product functionality reviewed.',
    '',
    'Needs Verification: Automated source review cannot determine conformance; runtime/manual testing is required.',
    '',
  ];

  for (const table of tables) {
    lines.push(`## ${table.title}`);
    lines.push('');
    lines.push('| Criteria | Compliance Requirement Summary | Conformance Level | Remarks and Explanations | How to Verify | How to Reproduce | Relevant Files |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const item of table.rows) {
      lines.push(`| ${cleanCell(item.criteria)} | ${cleanCell(item.requirementSummary)} | ${cleanCell(item.conformanceLevel)} | ${cleanCell(item.remarks)} | ${cleanCell(item.howToVerify)} | ${cleanCell(item.howToReproduce)} | ${cleanCell(item.relevantFiles)} |`);
    }
    lines.push('');
  }

  lines.push('## Summary');
  lines.push('');
  lines.push('This report is generated by the local `wcag-compliance-viewer` AI audit pipeline. Rows marked `Needs Verification`, `Mostly Supports`, or `Partially Supports` should be treated as test targets rather than final conformance certifications.');
  lines.push('');
  lines.push('Priority remediation items:');
  lines.push('');
  lines.push('1. Add a skip-to-main-content mechanism and a semantic main content landmark.');
  lines.push('2. Replace clickable non-interactive elements, such as the logo image navigation, with semantic buttons or links.');
  lines.push('3. Remove unnecessary `tabIndex={0}` from static text and non-interactive containers.');
  lines.push('4. Add route-specific document titles.');
  lines.push('5. Provide accessible names and equivalent data access for dashboard charts.');
  lines.push('6. Add explicit autocomplete tokens to login and POC fields where applicable.');
  lines.push('7. Expand Playwright runtime coverage with deeper workflow, contrast, zoom/reflow, and screen reader checks.');
  lines.push('');

  return lines.join('\n');
}
