/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/common-conditions/options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get published common condition options
     * @description Retrieve published common conditions for the approval dropdown.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of published common condition options */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommonConditionOptionsItem'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/published': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get paginated published common conditions
     * @description Retrieve the published common conditions for the admin table.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of results per page */
          pageSize?: number;
          /** @description Page number to retrieve */
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated list of published common conditions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedCommonConditionsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/submitted': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get paginated workflow common conditions
     * @description Retrieve draft, submitted, and rejected common conditions for the admin workflow table.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of results per page */
          pageSize?: number;
          /** @description Page number to retrieve */
          page?: number;
          /** @description Filter workflow common conditions by one or more statuses */
          statuses?: components['schemas']['CommonConditionWorkflowStatus'][];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated list of workflow common conditions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedCommonConditionsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/drafts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a common condition draft
     * @description Create a new draft common condition owned by the authenticated author.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CommonConditionCreateDraft'];
        };
      };
      responses: {
        /** @description Common condition draft created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/drafts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update a draft common condition
     * @description Update title and content for a draft common condition owned by the authenticated author.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CommonConditionCreateDraft'];
        };
      };
      responses: {
        /** @description Common condition draft updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Common condition not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict - invalid workflow state */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /**
     * Delete a common condition
     * @description Delete a common condition when permitted by role and workflow state. Federal users may delete only their own draft conditions, while NTIA may delete only final-stage approved or denied conditions.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Common condition deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid common condition id */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Common condition not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict - invalid workflow state */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/{id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a common condition draft
     * @description Transition a draft common condition to submitted for review.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Common condition draft submitted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid common condition id */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Common condition not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict - invalid workflow state */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/{id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Publish a submitted common condition
     * @description Transition a submitted common condition to published.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Common condition published successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid common condition id */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Common condition not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict - invalid workflow state */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/common-conditions/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject a submitted common condition
     * @description Transition a submitted common condition to rejected with a rejection reason.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CommonConditionReject'];
        };
      };
      responses: {
        /** @description Common condition rejected successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Common condition not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict - invalid workflow state */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/requests-over-time/{timeframe}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request submission metrics over a time period
     * @description Retrieve metrics showing the number of requests submitted during a specified timeframe
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time period to retrieve data for */
          timeframe: components['schemas']['Timeframe'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of requests submitted metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestsOverTimeData'][];
          };
        };
        /** @description Invalid timeframe parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/request-completion-time/{timeframe}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request completion time metrics over a time period
     * @description Retrieve metrics showing the average completion time for requests during a specified timeframe
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time period to retrieve data for */
          timeframe: components['schemas']['Timeframe'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of request completion time metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestCompletionTimeData'][];
          };
        };
        /** @description Invalid timeframe parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/requests-by-commercial-entity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request count by commercial entity
     * @description Retrieve the count of requests submitted by each commercial entity
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of request counts by commercial entity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestsByCommercialEntityData'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/requests-by-status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request count by status
     * @description Retrieve the count of requests grouped by their current status
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of request counts by status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestsByStatusData'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/request-drafts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all request drafts with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of request drafts (filtered by entity for COMMERCIAL users) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestDraft'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new request draft */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RequestDraft'];
        };
      };
      responses: {
        /** @description Request draft created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestDraft'];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/request-drafts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a request draft by ID with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description The ID of the request draft to retrieve */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Request draft found (access controlled by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestDraft'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request draft not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve paginated requests with entity-based filtering and unread message counts */
    get: {
      parameters: {
        query?: {
          /** @description Number of results per page */
          pageSize?: number;
          /** @description Page number to retrieve */
          page?: number;
          /** @description read boolean flag */
          unread?: boolean;
          /** @description Filter requests by one or more statuses */
          statuses?: components['schemas']['Status'][];
          /** @description Search for requests by call_sign or comments */
          search?: string;
          /** @description Field to sort request results by */
          sortBy?:
            | 'createdAt'
            | 'daysToOperation'
            | 'mission_name'
            | 'id'
            | 'launch_datetime_primary'
            | 'name_of_licensee'
            | 'primary_poc_email';
          /** @description Direction to sort request results */
          sortDirection?: 'asc' | 'desc';
          /** @description IANA timezone used to resolve relative and date-only filters */
          timezone?: string;
          /** @description ISO date-time used as the reference instant for days-to-operation filters */
          referenceDate?: string;
          /** @description JSON-encoded advanced request table filter rules for status, text, date, number, and exact launch serial number request fields */
          filterRules?: string;
          /** @description User ID for entity-based filtering. When provided, unreadMessageCount will be included for inquiries where the user's entity is involved (Commercial, Federal Agency, or NTIA). */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated list of request summaries with entity-based filtering and unread message counts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden - Access denied due to entity restrictions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Request'];
        };
      };
      responses: {
        /** @description Request created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a specific request */
    get: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Details of the request */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestDetails'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update a specific request */
    put: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Request'];
        };
      };
      responses: {
        /** @description Request updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/actions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all actions for a specific request with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get actions for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of actions for the given request (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Action'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/approvals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all approvals for a specific request with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get approvals for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of approvals for the given request (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Approval'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new approval for a specific request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Approval'];
        };
      };
      responses: {
        /** @description Approval created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all comments for a specific request with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get comments for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of comments for the given request (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Comment'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new comment for a specific request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Comment'];
        };
      };
      responses: {
        /** @description Comment created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/concurrences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all concurrences for a specific request with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get concurrences for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of concurrences for the given request (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Concurrence'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new concurrence for a specific request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Concurrence'];
        };
      };
      responses: {
        /** @description Concurrence created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/denials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all denials for a specific request with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get denials for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of denials for the given request (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Denial'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new denial for a specific request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Denial'];
        };
      };
      responses: {
        /** @description Denial created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/requested-revisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve the latest requested revisions for a given request_id with entity-based access control */
    get: {
      parameters: {
        query?: {
          /** @description User ID for entity-based access control filtering */
          user_id?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to get requested revision for */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Latest requested changes per the revision (filtered by entity for COMMERCIAL users when user_id is provided) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestedRevision'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new requested revision for a specific request */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          /** @description ID of the request to create a requested revision for */
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            requested_changes: string[];
            user_id: string;
          };
        };
      };
      responses: {
        /** @description Requested revision created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RequestedRevision'];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/revisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new revision for a specific request */
    post: {
      parameters: {
        query?: {
          /** @description Action parameter */
          action?: string;
        };
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Request'];
        };
      };
      responses: {
        /** @description Revision created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Request'];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/revisions/{revisionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all request revision for a specific request and revision id */
    get: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
          revisionId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Request revision */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Request'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/inquiries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve all inquiries for request */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of inquiries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Inquiry'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new Inquiry */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Inquiry'];
        };
      };
      responses: {
        /** @description inquiry created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/inquiries/{inquiryId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a specific inquiry */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
          inquiryId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description inquiry details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Inquiry'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description inquiry not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/requests/{id}/inquiries/{inquiryId}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new message */
    post: {
      parameters: {
        query?: never;
        header: {
          user_id: components['parameters']['UserIdHeader'];
          user_name: components['parameters']['UserNameHeader'];
          user_type: components['parameters']['UserTypeHeader'];
        };
        path: {
          id: number;
          inquiryId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Message'];
        };
      };
      responses: {
        /** @description message created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description inquiry not found */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{externalId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user by external ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The external ID of the user */
          externalId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
        /** @description External ID is required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/email/{email}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user by email */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The email address of the user */
          email: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserResponse'];
          };
        };
        /** @description Email is required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange authorization code for tokens
     * @description Exchanges an authorization code for access, refresh, and ID tokens. In login-gov mode, a code_verifier is required for PKCE. Protected by rate-limiting middleware.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            code: string;
            /** @description Required for PKCE in login-gov mode */
            code_verifier?: string;
          };
        };
      };
      responses: {
        /** @description Token exchange response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TokenResponse'];
          };
        };
        /** @description Missing code or code_verifier */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found in system */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to exchange authorization code */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh JWT token
     * @description Rotates refresh tokens and issues a new access token. Protected by rate-limiter.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description New JWT and refresh token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TokenResponse'];
          };
        };
        /** @description Missing or invalid refresh token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to refresh token */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserProfileResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found in system */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to retrieve user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout user and revoke refresh token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LogoutResponse'];
          };
        };
        /** @description Refresh token missing */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to logout */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get authentication configuration */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Auth config for frontend */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/debug-user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Debug user via authorization code */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            code: string;
          };
        };
      };
      responses: {
        /** @description Debug profile info */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DebugUserResponse'];
          };
        };
        /** @description Missing authorization code */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to retrieve debug user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Action: {
      action: components['schemas']['ActionType'];
      details?: string | null;
      /**
       * Format: date-time
       * @description Timestamp the action was created (ISO 8601 format with time zone)
       */
      createdAt?: string;
      federal_agency_abbr?: string | null;
      federal_agency_id?: number | null;
      federal_agency_name?: string | null;
      id?: number;
      request_id: number;
      user_id: string;
      user_name: string;
      user_type: components['schemas']['UserType'];
    };
    /** @enum {string} */
    ActionType:
      | 'approve'
      | 'finalize_denial'
      | 'approve_with_conditions'
      | 'concur'
      | 'concur_with_conditions'
      | 'not_concur'
      | 'request_revisions'
      | 'resubmit'
      | 'auto_approve';
    Approval: {
      condition: string;
      /**
       * Format: date-time
       * @description Timestamp the record was created in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Date approved in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      date_approved: string;
      id?: number;
      is_final?: boolean;
      read?: boolean;
      request_id: number;
      user_id?: string;
      /**
       * Format: date-time
       * @description Timestamp the record was updates in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      updatedAt?: string;
    };
    Comment: {
      comment: string;
      /**
       * Format: date-time
       * @description Timestamp the comment was created (ISO 8601 format with time zone)
       */
      createdAt?: string;
      federal_agency_abbr?: string;
      federal_agency_id?: number | null;
      federal_agency_name?: string;
      id?: number;
      is_internal?: boolean;
      request_id: number;
      user_id: string;
      user_name?: string;
      user_type?: components['schemas']['UserType'];
    };
    Concurrence: {
      concurred: boolean;
      conditions?: string;
      /**
       * Format: date-time
       * @description Timestamp the record was created in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      createdAt?: string;
      entity_abbr?: string | null;
      entity_id?: number | null;
      entity_name?: string | null;
      id?: number;
      request_id: number;
      /**
       * Format: date-time
       * @description Timestamp the record was updates in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      updatedAt?: string;
      user_id: string;
      user_name?: string;
      user_type?: components['schemas']['UserType'];
    };
    Denial: {
      /**
       * Format: date-time
       * @description Timestamp the record was created in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Date denied in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      date_denied: string;
      id?: number;
      is_final?: boolean;
      read?: boolean;
      /** @description Denial Reason. */
      reason: string;
      request_id: number;
      user_id?: string;
      /**
       * Format: date-time
       * @description Timestamp the record was updates in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      updatedAt?: string;
    };
    Receiver: {
      antenna_altitude?: number;
      /** @enum {string} */
      antenna_altitude_unit?: 'ft' | 'm' | 'km';
      antenna_beamwidth?: number;
      antenna_gain?: number;
      antenna_type?: string;
      /** Format: decimal */
      latitude_of_receiving_antenna?: number;
      /** @enum {string} */
      location_of_receiving_ground_station?:
        | 'first_stage'
        | 'second_stage'
        | 'ground';
      /** Format: decimal */
      longitude_of_receiving_antenna?: number;
      /** Format: date-time */
      transmission_end?: string;
      /** Format: date-time */
      transmission_start?: string;
    };
    Frequency: {
      /**
       * Format: date-time
       * @description Timestamp the record was created in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      createdAt?: string;
      /** Format: float */
      eirp: number;
      /** @enum {string} */
      eirp_unit: 'Watts' | 'dBW' | 'milliWatts' | 'dBm';
      /** Format: float */
      frequency: number;
      id?: number;
      /** @enum {string} */
      location_of_transmitter_on_vehicle_or_platform:
        | 'first_stage'
        | 'second_stage'
        | 'ground';
      /** Format: decimal */
      minus_20db_bandwidth: number;
      /** @enum {string} */
      minus_20db_bandwidth_before_or_after_filtering:
        | 'before_filtering'
        | 'after_filtering';
      /** Format: decimal */
      minus_3db_bandwidth: number;
      /** @enum {string} */
      minus_3db_bandwidth_before_or_after_filtering:
        | 'before_filtering'
        | 'after_filtering';
      /** Format: decimal */
      minus_60db_bandwidth: number;
      /** @enum {string} */
      minus_60db_bandwidth_before_or_after_filtering:
        | 'before_filtering'
        | 'after_filtering';
      nature_of_modulating_signals: string;
      emission_designator: string;
      request_id: number;
      /** Format: decimal */
      transmitted_bandwidth: number;
      /** @enum {string} */
      transmitted_bandwidth_is_signal_filtered: 'filtered' | 'not_filtered';
      transmitted_bandwidth_justification: string;
      tx_antenna_altitude: number;
      /** @enum {string} */
      tx_antenna_altitude_unit: 'ft' | 'm' | 'km';
      tx_antenna_beamwidth: number;
      tx_antenna_gain: number;
      tx_antenna_type: string;
      /**
       * Format: date-time
       * @description The end time of transmission in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      tx_transmission_end: string;
      /**
       * Format: date-time
       * @description The start time of transmission in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      tx_transmission_start: string;
      receivers: components['schemas']['Receiver'][];
      /**
       * Format: date-time
       * @description Timestamp the record was updates in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      updatedAt?: string;
    };
    FrequencyDraft: {
      /** Format: date-time */
      createdAt?: string;
      /** Format: float */
      eirp?: number;
      /** @enum {string} */
      eirp_unit?: 'Watts' | 'dBW' | 'milliWatts' | 'dBm';
      /** Format: float */
      frequency?: number;
      id?: number;
      /** @enum {string} */
      location_of_transmitter_on_vehicle_or_platform?:
        | 'first_stage'
        | 'second_stage'
        | 'ground';
      /** Format: decimal */
      minus_20db_bandwidth?: number;
      /** @enum {string} */
      minus_20db_bandwidth_before_or_after_filtering?:
        | 'before_filtering'
        | 'after_filtering';
      /** Format: decimal */
      minus_3db_bandwidth?: number;
      /** @enum {string} */
      minus_3db_bandwidth_before_or_after_filtering?:
        | 'before_filtering'
        | 'after_filtering';
      /** Format: decimal */
      minus_60db_bandwidth?: number;
      /** @enum {string} */
      minus_60db_bandwidth_before_or_after_filtering?:
        | 'before_filtering'
        | 'after_filtering';
      nature_of_modulating_signals?: string;
      emission_designator?: string;
      /** Format: decimal */
      transmitted_bandwidth?: number;
      /** @enum {string} */
      transmitted_bandwidth_is_signal_filtered?: 'filtered' | 'not_filtered';
      transmitted_bandwidth_justification?: string;
      tx_antenna_altitude?: number;
      /** @enum {string} */
      tx_antenna_altitude_unit?: 'ft' | 'm' | 'km';
      tx_antenna_beamwidth?: number;
      tx_antenna_gain?: number;
      tx_antenna_type?: string;
      /** Format: date-time */
      tx_transmission_end?: string;
      /** Format: date-time */
      tx_transmission_start?: string;
      receivers?: components['schemas']['Receiver'][];
      /** Format: date-time */
      updatedAt?: string;
    };
    Request: {
      /** Format: binary */
      ecf_cartesian_vectors_format_file: string;
      /** Format: binary */
      ground_track_of_launch_vehicle_2d_img_file: string;
    } & components['schemas']['RequestFrequencyBase'];
    RequestBase: {
      /** Format: email */
      alternate_poc_email: string;
      alternate_poc_name: string;
      alternate_poc_phone: string;
      call_sign: string;
      city: string;
      /**
       * Format: date-time
       * @description Timestamp the record was created in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      createdAt?: string;
      current_revision?: boolean;
      ecf_cartesian_vectors_format_file_desc: string;
      /**
       * Format: date-time
       * @description This is optionally entered by the user and is stored as an ISO date-time Zulu, otherwise defaults to current date-time
       */
      fcc_filing_date?: string;
      ground_track_from_liftoff_until_payload_separation: string;
      ground_track_of_launch_vehicle_2d_img_file_desc: string;
      id?: number;
      user_id: string;
      /** Format: decimal */
      latitude: number;
      /**
       * Format: date-time
       * @description The end time of launch in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      launch_datetime_backup: string;
      /**
       * Format: date-time
       * @description The start time of launch in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      launch_datetime_primary: string;
      /** Format: decimal */
      longitude: number;
      mission_name: string;
      name_of_launch_vehicle: string;
      name_of_licensee: string;
      number_of_frequencies: number;
      orbital_location?: string;
      /** Format: email */
      primary_poc_email: string;
      primary_poc_name: string;
      primary_poc_phone: string;
      read?: boolean;
      revision: number;
      root_request_id?: number;
      state: string;
      status: components['schemas']['Status'];
      /**
       * Format: date-time
       * @description Timestamp the record was updated in ISO 8601 format with time zone (e.g., "2024-12-09T15:30:00Z").
       */
      updatedAt?: string;
    };
    RequestSummary: {
      /** @description Array of frequency values for this request */
      frequencies: number[];
      /**
       * @description Number of unread messages in inquiries where the user's entity is involved. Only included when user_id parameter is provided, entity-based filtering is applied, and count is greater than 0. Omitted when count is 0 or user's entity is not involved in any inquiries for this request.
       * @example 3
       */
      unreadMessageCount?: number;
    } & components['schemas']['RequestBase'];
    /**
     * @example {
     *       "data": [
     *         {
     *           "id": 20,
     *           "mission_name": "Launch Request 1",
     *           "name_of_licensee": "Commercial Corp",
     *           "call_sign": "COMM1",
     *           "status": "UNDER_NTIA_INITIAL_REVIEW",
     *           "frequencies": [
     *             2400,
     *             2450
     *           ],
     *           "unreadMessageCount": 2
     *         },
     *         {
     *           "id": 21,
     *           "mission_name": "Launch Request 2",
     *           "name_of_licensee": "NASA Request",
     *           "call_sign": "NASA1",
     *           "status": "UNDER_FEDERAL_AGENCIES_REVIEW",
     *           "frequencies": [
     *             2500
     *           ]
     *         }
     *       ],
     *       "totalCount": 150,
     *       "totalPages": 15
     *     }
     */
    RequestsResponse: {
      /** @description Array of request summaries with entity-based filtering applied */
      data: components['schemas']['RequestSummary'][];
      /**
       * @description Total number of requests matching the filter criteria
       * @example 150
       */
      totalCount: number;
      /**
       * @description Total number of pages based on pageSize
       * @example 15
       */
      totalPages: number;
    };
    RequestDetails: {
      /** @description file content is base64 encoded */
      ecf_cartesian_vectors_format_file: string;
      /** @description file content is base64 encoded */
      ground_track_of_launch_vehicle_2d_img_file: string;
    } & components['schemas']['RequestFrequencyBase'];
    RequestDraft: {
      alternate_poc_email?: string;
      alternate_poc_name?: string;
      alternate_poc_phone?: string;
      call_sign?: string;
      city?: string;
      /** Format: date-time */
      createdAt?: string;
      /** @description file content is base64 encoded */
      ecf_cartesian_vectors_format_file?: string;
      ecf_cartesian_vectors_format_file_desc?: string;
      ecf_cartesian_vectors_format_file_path?: string;
      /** Format: date-time */
      fcc_filing_date?: string;
      frequencies?: components['schemas']['FrequencyDraft'][];
      ground_track_from_liftoff_until_payload_separation?: string;
      /** @description file content is base64 encoded */
      ground_track_of_launch_vehicle_2d_img_file?: string;
      ground_track_of_launch_vehicle_2d_img_file_desc?: string;
      ground_track_of_launch_vehicle_2d_img_file_path?: string;
      id?: number;
      /** Format: decimal */
      latitude?: number;
      /** Format: date-time */
      launch_datetime_backup?: string;
      /** Format: date-time */
      launch_datetime_primary?: string;
      /** Format: decimal */
      longitude?: number;
      mission_name?: string;
      name_of_launch_vehicle?: string;
      name_of_licensee?: string;
      number_of_frequencies?: number;
      orbital_location?: string;
      primary_poc_email?: string;
      primary_poc_name?: string;
      primary_poc_phone?: string;
      state?: string;
      /** Format: date-time */
      updatedAt?: string;
      user_id: string;
    };
    RequestFrequencyBase: {
      frequencies: components['schemas']['Frequency'][];
    } & components['schemas']['RequestBase'];
    RequestList: {
      /** @description file content is base64 encoded */
      ecf_cartesian_vectors_format_file?: string;
      /** @description Array of frequencies (as floats) */
      frequencies?: number[];
      /** @description file content is base64 encoded */
      ground_track_of_launch_vehicle_2d_img_file?: string;
    } & components['schemas']['RequestBase'];
    RequestedRevision: {
      /**
       * Format: date-time
       * @description Timestamp the revision was created (ISO 8601 format with time zone)
       */
      createdAt?: string;
      id?: number;
      requested_changes: string[];
      /**
       * Format: date-time
       * @description Timestamp the revision was last updated (ISO 8601 format with time zone)
       */
      updatedAt?: string;
      user_id: string;
    };
    Message: {
      id?: number;
      inquiry_id: number;
      sender_id: number;
      content: string;
      /**
       * Format: date-time
       * @description Timestamp the revision was created (ISO 8601 format with time zone)
       */
      sentAt: string;
    };
    MessageResponse: {
      id?: number;
      inquiry_id: number;
      user?: components['schemas']['User'];
      content: string;
      /**
       * Format: date-time
       * @description Timestamp the revision was created (ISO 8601 format with time zone)
       */
      sentAt: string;
    };
    Inquiry: {
      id?: number;
      request_id: number;
      entityA_id: number;
      entityB_id: number;
      closed?: boolean;
      closedBy_id?: number;
      /**
       * Format: date-time
       * @description Timestamp the comment was created (ISO 8601 format with time zone)
       */
      closedAt?: string;
      /**
       * Format: date-time
       * @description Timestamp the comment was created (ISO 8601 format with time zone)
       */
      createdAt: string;
      messages: components['schemas']['Message'][];
    };
    InquiryResponse: {
      id?: number;
      request_id: number;
      entityA_id: number;
      entityB_id: number;
      closed?: boolean;
      closedBy?: components['schemas']['User'];
      /**
       * Format: date-time
       * @description Timestamp the comment was created (ISO 8601 format with time zone)
       */
      closedAt?: string;
      /**
       * Format: date-time
       * @description Timestamp the comment was created (ISO 8601 format with time zone)
       */
      createdAt: string;
      messages: components['schemas']['MessageResponse'][];
    };
    User: {
      id?: number;
      external_id: string;
      name: string;
      email: string;
      entity_id: number;
      /** @description Whether the user can submit concurrences */
      can_concur: boolean;
      entity?: components['schemas']['Entity'];
      messages: components['schemas']['Message'][];
      closedInquiries: components['schemas']['Inquiry'][];
    };
    UserResponse: {
      id: number;
      external_id: string;
      name: string;
      email: string;
      entity_id: number;
      /** @description Whether the user can submit concurrences */
      can_concur: boolean;
      entity: {
        id?: number;
        name?: string;
        abbreviation?: string;
        type?: components['schemas']['UserType'];
      };
    };
    Entity: {
      id?: number;
      abbreviation: string;
      name: string;
      type: components['schemas']['UserType'];
      active: boolean;
      users?: components['schemas']['User'];
      inquiriesAsEntityA: components['schemas']['Inquiry'][];
      inquiriesAsEntityB: components['schemas']['Inquiry'][];
    };
    /** @enum {string} */
    Status:
      | 'SUBMITTED'
      | 'UNDER_NTIA_INITIAL_REVIEW'
      | 'UNDER_INITIAL_REVISION_PER_NTIA'
      | 'UNDER_FEDERAL_AGENCIES_REVIEW'
      | 'UNDER_NTIA_FINAL_REVIEW'
      | 'UNDER_FINAL_REVISION_PER_NTIA'
      | 'DENIED'
      | 'APPROVED'
      | 'APPROVED_WITH_CONDITIONS';
    /** @enum {string} */
    UserType: 'COMMERCIAL' | 'FEDERAL_AGENCY' | 'NTIA';
    /** @enum {string} */
    Timeframe: 'week' | 'month' | 'quarter';
    RequestsOverTimeData: {
      total_requests: number;
    };
    RequestCompletionTimeData: {
      total_completed: number;
      avg_days: number;
      fastest_days: number;
      slowest_days: number;
    };
    RequestsByCommercialEntityData: {
      entity_id: number;
      entity_name: string;
      total_submissions: number;
    };
    RequestsByStatusData: {
      status_group: string;
      request_count: number;
    };
    TokenResponse: {
      access_token: string;
      refresh_token: string;
      id_token?: string;
      expires_in: number;
      refresh_token_expires_in?: number;
      /** @example Bearer */
      token_type: string;
      user?: components['schemas']['UserObject'];
    };
    UserProfileResponse: {
      id?: string;
      name?: string;
      displayName?: string;
      email: string;
      entity?: components['schemas']['Entity'];
      can_concur?: boolean;
      isEntityActive?: boolean;
      /** @description Raw provider profile */
      auth_profile?: Record<string, never>;
      sub?: string;
      given_name?: string;
      family_name?: string;
    };
    LogoutResponse: {
      message: string;
      logout_redirect_url?: string | null;
    };
    ConfigResponse: {
      authMode: string;
      entraConfigured: boolean;
      loginGovConfigured: boolean;
      loginGovClientId?: string | null;
      loginGovRedirectUri?: string | null;
      loginGovAuthEndpoint?: string | null;
      loginGovEndSessionEndpoint?: string | null;
    };
    DebugUserResponse: {
      message: string;
      userProfile: components['schemas']['UserProfileResponse'];
      instructions: string;
    };
    UserObject: {
      id: string;
      displayName: string;
      email: string;
      role: string;
      tenantId: string;
      federalAgencyId?: string | null;
      federalAgencyAbbr?: string | null;
      canConcur: boolean;
      isEntityActive?: boolean;
    };
    CommonConditionCreateDraft: {
      title: string;
      content: string;
    };
    CommonCondition: {
      id: number;
      title: string;
      content: string;
      status: components['schemas']['CommonConditionWorkflowStatus'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      publishedAt: string | null;
      submittedBy: string | null;
      isOwnedByCurrentUser: boolean;
      rejectionReason: string | null;
    };
    CommonConditionOptionsItem: {
      id: number;
      title: string;
      content: string;
      sortOrder: number;
    };
    CommonConditionReject: {
      rejectionReason: string;
    };
    /** @enum {string} */
    CommonConditionWorkflowStatus:
      | 'DRAFT'
      | 'SUBMITTED'
      | 'REJECTED'
      | 'PUBLISHED';
    PaginatedCommonConditionsResponse: {
      page: number;
      pageSize: number;
      totalCount: number;
      totalPages: number;
      data: components['schemas']['CommonCondition'][];
    };
  };
  responses: {
    /**
     * @description Access denied due to entity-based access control restrictions.
     *     COMMERCIAL users can only access data related to requests created by their own entity.
     */
    AccessDenied: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @example Users can only view data created by their own entity */
          error?: string;
        };
      };
    };
    /**
     * @description Response filtered based on user's entity type:
     *     - COMMERCIAL users see only data from their own entity
     *     - NTIA and FEDERAL_AGENCY users see all data
     */
    EntityFilteredResponse: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
  };
  parameters: {
    UserIdHeader: string;
    UserNameHeader: string;
    UserTypeHeader: components['schemas']['UserType'];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
